IIC_MOD_DIR := $(USERMOD_DIR)
SRC_USERMOD_C += $(EXAMPLE_MOD_DIR)/24cxx.c
SRC_USERMOD_C += $(EXAMPLE_MOD_DIR)/xl9555.c
SRC_USERMOD_C += $(EXAMPLE_MOD_DIR)/ap3216c.c
SRC_USERMOD_C += $(EXAMPLE_MOD_DIR)/qma6100p.c
SRC_USERMOD_C += $(EXAMPLE_MOD_DIR)/oled.c
